# Form implementation generated from reading ui file 'add_to_t.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_tovar(object):
    def setupUi(self, add_tovar):
        add_tovar.setObjectName("add_tovar")
        add_tovar.resize(711, 444)
        add_tovar.setStyleSheet("background-color: rgb(250, 190, 255);\n"
"font: 8pt \"New York\";")
        self.add_in_trash = QtWidgets.QPushButton(parent=add_tovar)
        self.add_in_trash.setGeometry(QtCore.QRect(20, 240, 81, 31))
        self.add_in_trash.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"border-radius:10px;\n"
"font: 10pt \"MS Sans Serif\";")
        self.add_in_trash.setObjectName("add_in_trash")
        self.cntEdit = QtWidgets.QLineEdit(parent=add_tovar)
        self.cntEdit.setGeometry(QtCore.QRect(50, 40, 141, 21))
        self.cntEdit.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"font: 10pt \"MS Sans Serif\";")
        self.cntEdit.setObjectName("cntEdit")
        self.lengEdit = QtWidgets.QLineEdit(parent=add_tovar)
        self.lengEdit.setGeometry(QtCore.QRect(50, 70, 141, 21))
        self.lengEdit.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"font: 10pt \"MS Sans Serif\";")
        self.lengEdit.setObjectName("lengEdit")
        self.weigEdit = QtWidgets.QLineEdit(parent=add_tovar)
        self.weigEdit.setGeometry(QtCore.QRect(50, 100, 141, 21))
        self.weigEdit.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"font: 10pt \"MS Sans Serif\";")
        self.weigEdit.setText("")
        self.weigEdit.setObjectName("weigEdit")
        self.back = QtWidgets.QPushButton(parent=add_tovar)
        self.back.setGeometry(QtCore.QRect(120, 240, 81, 31))
        self.back.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"border-radius:10px;\n"
"font: 10pt \"MS Sans Serif\";")
        self.back.setObjectName("back")
        self.tableWidget = QtWidgets.QTableWidget(parent=add_tovar)
        self.tableWidget.setGeometry(QtCore.QRect(270, 20, 391, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(parent=add_tovar)
        self.comboBox.setGeometry(QtCore.QRect(50, 180, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(parent=add_tovar)
        self.label.setGeometry(QtCore.QRect(40, 140, 161, 31))
        self.label.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"font: 10pt \"MS Sans Serif\";")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(add_tovar)
        QtCore.QMetaObject.connectSlotsByName(add_tovar)

    def retranslateUi(self, add_tovar):
        _translate = QtCore.QCoreApplication.translate
        add_tovar.setWindowTitle(_translate("add_tovar", "Form"))
        self.add_in_trash.setText(_translate("add_tovar", "Добавить"))
        self.cntEdit.setPlaceholderText(_translate("add_tovar", "Количество"))
        self.lengEdit.setPlaceholderText(_translate("add_tovar", "Длина"))
        self.weigEdit.setPlaceholderText(_translate("add_tovar", "Ширина"))
        self.back.setText(_translate("add_tovar", "Назад"))
        self.label.setText(_translate("add_tovar", "Выберите вариант из списка справа:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_tovar = QtWidgets.QWidget()
    ui = Ui_add_tovar()
    ui.setupUi(add_tovar)
    add_tovar.show()
    sys.exit(app.exec())
