# Form implementation generated from reading ui file 'admw.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_admin_form(object):
    def setupUi(self, admin_form):
        admin_form.setObjectName("admin_form")
        admin_form.resize(770, 428)
        admin_form.setStyleSheet("background-color: rgb(250, 190, 255);\n"
"font: 8pt \"New York\";")
        self.tableWidget = QtWidgets.QTableWidget(parent=admin_form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 20, 541, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.change_b = QtWidgets.QPushButton(parent=admin_form)
        self.change_b.setGeometry(QtCore.QRect(170, 370, 111, 31))
        self.change_b.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"border-radius:10px;\n"
"font: 10pt \"MS Sans Serif\";")
        self.change_b.setObjectName("change_b")
        self.back = QtWidgets.QPushButton(parent=admin_form)
        self.back.setGeometry(QtCore.QRect(350, 370, 81, 31))
        self.back.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"border-radius:10px;\n"
"font: 10pt \"MS Sans Serif\";")
        self.back.setObjectName("back")
        self.comboBox = QtWidgets.QComboBox(parent=admin_form)
        self.comboBox.setGeometry(QtCore.QRect(600, 30, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(2, "")

        self.retranslateUi(admin_form)
        QtCore.QMetaObject.connectSlotsByName(admin_form)

    def retranslateUi(self, admin_form):
        _translate = QtCore.QCoreApplication.translate
        admin_form.setWindowTitle(_translate("admin_form", "Администрация"))
        self.change_b.setText(_translate("admin_form", "Изменить"))
        self.back.setText(_translate("admin_form", "Назад"))
        self.comboBox.setItemText(0, _translate("admin_form", "По возрастанию"))
        self.comboBox.setItemText(1, _translate("admin_form", "По убыванию"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin_form = QtWidgets.QWidget()
    ui = Ui_admin_form()
    ui.setupUi(admin_form)
    admin_form.show()
    sys.exit(app.exec())
