# Form implementation generated from reading ui file 'authw2.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_auth2(object):
    def setupUi(self, auth2):
        auth2.setObjectName("auth2")
        auth2.resize(186, 209)
        auth2.setStyleSheet("background-color: rgb(250, 190, 255);\n"
"font: 8pt \"New York\";")
        self.polz_b = QtWidgets.QPushButton(parent=auth2)
        self.polz_b.setGeometry(QtCore.QRect(30, 60, 111, 31))
        self.polz_b.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"border-radius:10px;\n"
"font: 10pt \"MS Sans Serif\";")
        self.polz_b.setObjectName("polz_b")
        self.adm_b = QtWidgets.QPushButton(parent=auth2)
        self.adm_b.setGeometry(QtCore.QRect(50, 110, 81, 31))
        self.adm_b.setStyleSheet("background-color: rgb(255, 247, 213);\n"
"border-radius:10px;\n"
"font: 10pt \"MS Sans Serif\";")
        self.adm_b.setObjectName("adm_b")

        self.retranslateUi(auth2)
        QtCore.QMetaObject.connectSlotsByName(auth2)

    def retranslateUi(self, auth2):
        _translate = QtCore.QCoreApplication.translate
        auth2.setWindowTitle(_translate("auth2", "Hello"))
        self.polz_b.setText(_translate("auth2", "Пользователь"))
        self.adm_b.setText(_translate("auth2", "Админ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    auth2 = QtWidgets.QWidget()
    ui = Ui_auth2()
    ui.setupUi(auth2)
    auth2.show()
    sys.exit(app.exec())
